#+title: 6 4

* Try It / Solve It
1. Describe the benefit of using one or more parameters with a cursor.
2. Write a PL/SQL block to display the country name and the area of each country in a chosen region. The region_id should be passed to the cursor as a parameter. Test your block using two region_ids: 5 (South America) and 30 (Eastern Asia). Do not use a cursor FOR loop.
3. Modify your answer to question 2 to use a cursor FOR loop. You must still declare the cursor explicitly in the DECLARE section. Test it again using regions 5 and 30.
4. Modify your answer to question 3 to display the country_name and area of each country in a chosen region that has an area greater than a specific value. The region_id and specific area should be passed to the cursor as two parameters. Test your block twice using region_id 5 (South America): the first time with area = 200000 and the second time with area = 1000000.
5. Modify your answer to question 4 to fetch and display two sets of countries in a single execution of the block. You should open and close the cursor twice, passing different parameter values to it each time. Before each set of output rows, display the message “Region: <region_id> Minimum Area: <area>”., for example “Region: 5 Minimum Area: 200000”. Test your changes using (5, 200000) and (30, 500000).
