CREATE TABLE IF NOT EXISTS "USERS" (
    enrollment INT PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    team_id INT NOT NULL REFERENCES TEAMS(team_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CREDENTIALS" (
    enrollment TEXT NOT NULL REFERENCES USERS(enrollment) ON DELETE CASCADE,
    password TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS "TEAMS" (
    team_id INT PRIMARY KEY NOT NULL,
    team_name TEXT NOT NULL,
    captain INT NOT NULL,
    FOREIGN KEY (captain) REFERENCES USERS(enrollment) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "GAMES" (
    game_id INT PRIMARY KEY NOT NULL,
    team_A INT NOT NULL,
    team_B INT NOT NULL,
    FOREIGN KEY (team_A) REFERENCES TEAMS(team_id) ON DELETE CASCADE,
    FOREIGN KEY (team_B) REFERENCES TEAMS(team_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "GAMES_HISTORY" (
    game_id INT PRIMARY KEY REFERENCES GAMES (game_id),
    winner_team INT NOT NULL REFERENCES TEAMS(team_id) ON DELETE CASCADE,
);

CREATE TABLE IF NOT EXISTS "HISTORY" (
    history_id INT PRIMARY KEY NOT NULL,
    game_id INT NOT NULL,
    winner_team_id INT NOT NULL,
    winning_date DATE NOT NULL,
    FOREIGN KEY (game_id) REFERENCES GAMES(game_id) ON DELETE CASCADE,
    FOREIGN KEY (winner_team_id) REFERENCES TEAMS(team_id) ON DELETE CASCADE
);
