#+title: 2-4 PL/SQL
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}

* Vocabulary
1. BOOLEAN Data Type
2. %TYPE Attribute

* Try It/Solve It
1. Declarations
   1. Which of the following variable declarations are valid?
      a. Valid
      b. Invalid
      c. Invalid
      d. Valid
   2. For the invalid declarations above, describe why they are invalid.
      1. B option: All strings must be inside quotation marks.
      2. C option: Variables must be initialized during declaration.
   3. Write an anonymous block in which you declare and print (on the screen) each of thevariables in 1A above, correcting the invalid declarations and adding information as needed.
      #+begin_src sql
        DECLARE
            number_of_students PLS_INTEGER := 30;
            student_name VARCHAR2(10) := 'Johnson';
            stu_per_class CONSTANT NUMBER := 1;
            today DATE := SYSDATE + 1;
        BEGIN
            DBMS_OUTPUT.PUT_LINE ('The number of students is:' || number_of_students || '.');
            DBMS_OUTPUT.PUT_LINE ('The name of the students is:' || student_name || '.');
            DBMS_OUTPUT.PUT_LINE ('The number of students per class is:' || stu_per_class || '.');
            DBMS_OUTPUT.PUT_LINE ('Tomorrows date is: ' || today || '.');
        END
      #+end_src
2. Evaluate the variables in the following code. Answer the following questions about each variable. Is it named well? Why or why not? If it is not named well, what would be a better name and why?
   #+begin_src sql
     DECLARE
         country_name VARCHAR2(50);
         median_age  NUMBER(6, 2);
     BEGIN
     SELECT country_name, median_age INTO country_name, median_age
         FROM countries
     WHERE country_name = 'Japan';
         DBMS_OUTPUT.PUT_LINE('The median age in '|| country_name
                                   || ' is ' || median_age || '.');
     END;
   #+end_src

   *The two variables have the same name as the database columns.*

3. Change the declarations in 2) above so they use the %TYPE attribute
   1. =country_name wf_countries.country_name%TYPE;=
   2. =median_age wf_countries.median_age%TYPE;=

4. In your own words, describe why using the %TYPE attribute is better than hard-coding data types. Can you explain how you could run into problems in the future by hard-coding the data types of the country_name and median_age variables in question 2?

   *It's more sustainable in the future, it brings adaptability and reduces maintenance*

5. Create the following anonymous block:
   #+begin_src sql
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Hello World');
    END;
   #+end_src
   1. Add a declarative section to this PL/SQL block. In the declarative section, declare the following variables:
      1. A variable named TODAY of datatype DATE. Initialize TODAY with SYSDATE.
      2. A variable named TOMORROW with the same datatype as TODAY. Use the %TYPE attribute
      #+begin_src sql
      DECLARE
          today DATE:=SYSDATE;
          tomorrow today%TYPE;
      BEGIN
          DBMS_OUTPUT.PUT_LINE('Hello World');
      END;
      #+end_src

   2. In the executable section, initialize the TOMORROW variable with an expression that calculates tomorrow’s date (add 1 to the value in TODAY). Print the value of TODAY and TOMORROW after printing ‘Hello World’.
      #+begin_src sql
        DECLARE
            today DATE:=SYSDATE;
            tomorrow today%TYPE;
        BEGIN
            tomorrow := today + 1;
            DBMS_OUTPUT.PUT_LINE('Hello World');
            DBMS_OUTPUT.PUT_LINE(today);
            DBMS_OUTPUT.PUT_LINE(tomorrow);
        END;
      #+end_src
